### ISSUE TITLE
Configurable table, column and index names [feature]

### ISSUE THREAD

**Issue by denis111** [halfbaked/grails-localizations#19]
What about this?
We are migrating from another platform to grails and as we also had translations in the database we use this wonderful plugin but i have to mantain my own copy of the plugin with changed column names :(.

**Comment by halfbaked** [comment]
Hi Denis,
Pull requests or indeed a collaborator are welcome. 
If you are interested I can add you this repo as a contributor - or something like that.

**Comment by halfbaked** [comment]
published as 2.4
