### ISSUE TITLE
It doesn't update old code text values from files at startup.

### ISSUE THREAD

**Issue by vsachinv** [halfbaked/grails-localizations#24]
Lets say, We wanted to change text message of a code to different value. It doesn't update them automatically at startup.

**Comment by halfbaked** [comment]
there is some in memory caching. If you look at the code you should find
how to clear that cache after making a change.

**Comment by vsachinv** [comment]
@halfbaked No not caching issue. It's related to DB side entries data update from message.properties when a already added message.properties code text has been updated in the file but not syncing the DB.

**Comment by vsachinv** [comment]
@halfbaked Thats something i needed to call Localization.reload(). I got that later. Its just to let everyone know as well.
